### ISSUE TITLE
Music stops playing and spamming LUA errors (and others)

### ISSUE THREAD

**Issue by syahmiasyraff02** [relaxtakenotes/gm-action-music#9]
I was playing the game for a couple of hours after the update of this addon was released and out of nowhere, the music stopped playing and spammed me with the following error messages in the console window and the problems tab.
[Action Music (with pvp support)] lua/autorun/client/am_music.lua:405: bad argument #1 to 'PlayFile' (string expected, got nil)
  1. PlayFile - [C]:-1
   2. unknown - lua/autorun/client/am_music.lua:405

Timer Failed! [Simple][@lua/autorun/client/am_music.lua (line 377)]

[Action Music (with pvp support)] lua/autorun/client/am_music.lua:523: table index is nil
  1. v - lua/autorun/client/am_music.lua:523
   2. unknown - lua/includes/modules/hook.lua:96 (x62)

Disabling and reenabling the music, reshuffling the music and initialize the music didn't work. This issue only solved after I restart the map. Unfortunately, I couldn't be able to record it for you because it happened randomly.

**Comment by relaxtakenotes** [comment]
what are your packs? it might help me reproduce the issue

**Comment by relaxtakenotes** [comment]
also what is the value of cl_am_continue_songs?

**Comment by relaxtakenotes** [comment]
oh and if you can reproduce it yourself again, please have developer 1 enabled. thanks.

**Comment by syahmiasyraff02** [comment]
> what are your packs? it might help me reproduce the issue

Sorry for a late response, but here's the list if you're curious:

1. Action Music: Call of Duty: Original Modern Warfare Trilogy (2007-2011)
2. Nombat - COD: BOCW by iiNS
3. Nombat - MW2019 OST
4. Nombat - Modern Warfare II

> also what is the value of cl_am_continue_songs for you?

cl_am_continue_songs 1

**Comment by relaxtakenotes** [comment]
either way i already pushed a potential fix to workshop. see if that helps

**Comment by syahmiasyraff02** [comment]
> either way i already pushed a potential fix to workshop. see if that helps

The issue still occurs and it happened again just a couple of minutes ago. I think it happened because the addon bugs itself after constantly changing the music type at a short interval (between tens of seconds and a minute). I also noticed that as I'm playing a map where the enemy NPCs is spawned by the map itself via a script (e.g. custom campaigns), the music type temporarily changes from Ambient to either Battle of Intensive Battle depending on how many enemy NPCs there are despite the fact that they're behind the wall before switching back to Ambient.

**Comment by relaxtakenotes** [comment]
play around with these commands to alleviate the latter issue:
sv_am_enemy_threshold - should probably set it higher
sv_am_allow_alternate_trigger - try turning this off
sv_am_targeted_timer - should probably set it higher

i'll look further into the first issue.

**Comment by relaxtakenotes** [comment]
try the github version, pushed some changes that i'm not yet comfortable pushing to the workshop

**Comment by syahmiasyraff02** [comment]
> try the github version, pushed some changes that i'm not yet comfortable pushing to the workshop

Unfortunately, I can't get the current github build to work.

Speaking of the second issue, I kinda fixed it by enabling the sv_am_expensive_hidden_checks command. Another issue I have with this addon is for example, I have 13 enemy NPCs (enough to trigger the Intensive Battle music as I set in the sv_am_enemy_threshold command value to 10) with 3 in front of me and the rest being hidden, whenever I killed one of them in front of me, the rest of the enemy NPCs (including the hidden ones) will alert my presence and the Intensive Battle music plays instead of the regular Battle music despite the hidden ones are, well, hidden from my vision.

**Comment by relaxtakenotes** [comment]
just the unfortunate side effects of trying to dynamically play songs. also i was able to finally reproduce the issue myself, so i'm able to come up with a solution

**Comment by syahmiasyraff02** [comment]
> just the unfortunate side effects of trying to dynamically play songs. also i was able to finally reproduce the issue myself, so i'm able to come up with a solution

Which issue, the lua errors I mentioned in the OP?

I'm still testing the current github build. If this issue is resolved, you can revert back to the reshuffle system you've updated a couple of days ago.

**Comment by relaxtakenotes** [comment]
the original issue you reported, yes. there's nothing i can do against the other issues you mentioned as really it performs as intended, mess around with sv_am commands as i said

**Comment by relaxtakenotes** [comment]
pushed another update to the github version. bug should be fixed now i hope? if not, there's a bit more debug messages that get printed out to the console which should help

**Comment by syahmiasyraff02** [comment]
> pushed another update to the github version. bug should be fixed now i hope? if not, there's a bit more debug messages that get printed out to the console which should help

I just tested on a custom campaign where the music type constantly changes at a short interval and so far, no issues. I guess this issue has been fixed, for now. You can revert the temporary music reshuffle system you introduced in the last couple of GitHub builds to the Workshop one (smart reshuffle) you introduced a couple of days ago with the added fix from the latest build.

**Comment by relaxtakenotes** [comment]
fyi i never changed smart reshuffle's behaviour in these recent patches

**Comment by syahmiasyraff02** [comment]
> fyi i never changed smart reshuffle's behaviour in these recent patches

Thats's weird because I noticed that in the recent GitHub builds, the music always reshuffles when the music type changes despite the song isn't over. You mentioned that I could get back to the old reshuffle system by setting the cl_am_reshuffle_pack_period command value to 1, which is what I did. Before I made this post, the old reshuffle system worked as intended by setting that value in the console command until the last couple of GitHub builds.
